# Generated by Django 2.1.4 on 2019-01-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='areas_of_interest',
            field=models.CharField(default='Bienen', max_length=100),
        ),
    ]
