# Generated by Django 2.1.4 on 2019-01-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='areas_of_interest',
            field=models.CharField(blank=True, max_length=100, verbose_name='areas_of_interest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, max_length=4000, verbose_name='bio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.CharField(blank=True, max_length=30, verbose_name='birth_date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, verbose_name='phone_number'),
        ),
    ]
