# Generated by Django 2.1.4 on 2019-01-14 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20190114_1803'),
        ('profiles', '0002_auto_20190112_1221'),
    ]

    operations = [
    ]
