# Generated by Django 2.1.4 on 2019-01-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190121_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('de', 'German')], default='en-us', max_length=10),
        ),
    ]
