# Generated by Django 2.1.4 on 2019-01-18 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_merge_20190114_1905'),
        ('profiles', '0003_auto_20190115_0818'),
    ]

    operations = [
    ]
