# Generated by Django 2.1.4 on 2019-01-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriesofmeasurement',
            name='dataset',
        ),
        migrations.DeleteModel(
            name='SeriesOfMeasurement',
        ),
    ]
