# Generated by Django 2.1.4 on 2019-01-20 19:12

from django.db import migrations
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20190120_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markupfield.fields.MarkupField(rendered_field=True, verbose_name='description'),
        ),
    ]
