# Generated by Django 2.1.4 on 2019-01-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
