# Generated by Django 2.1.4 on 2019-01-19 11:20

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190118_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='_description_rendered',
            field=models.TextField(default=' ', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='description_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown'), ('restructuredtext', 'Restructured Text')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markupfield.fields.MarkupField(rendered_field=True),
        ),
    ]
