# Generated by Django 2.1.4 on 2019-01-07 18:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190107_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 7, 18, 38, 24, 845458, tzinfo=utc)),
        ),
    ]
