# Generated by Django 2.1.4 on 2019-01-07 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190107_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
