# Generated by Django 2.1.4 on 2019-01-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20190121_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=models.ImageField(default='images/None/placeProject.png', upload_to='images/', verbose_name='picture'),
        ),
    ]
