# Generated by Django 2.1.4 on 2019-01-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_dataset_data_file_link'),
        ('projects', '0007_auto_20190122_1829'),
    ]

    operations = [
    ]
