# Generated by Django 2.1.5 on 2019-01-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_merge_20190122_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='label_x',
            field=models.CharField(blank=True, max_length=30, verbose_name='Label X'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='label_y',
            field=models.CharField(blank=True, max_length=30, verbose_name='Label Y'),
        ),
    ]
