# Generated by Django 2.1.5 on 2019-01-26 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_auto_20190126_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='title',
            field=models.CharField(max_length=30, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=30, verbose_name='title'),
        ),
        migrations.AlterUniqueTogether(
            name='dataset',
            unique_together={('title', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('title', 'user')},
        ),
    ]
