# Generated by Django 2.1.4 on 2019-01-10 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20190107_1855'),
        ('projects', '0004_auto_20190107_2002'),
    ]

    operations = [
    ]
