# Generated by Django 2.1.5 on 2019-01-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20190126_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-updated',)},
        ),
    ]
