# Generated by Django 2.1.5 on 2019-01-26 14:28

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20190120_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='support',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='_about_text_rendered',
            field=models.TextField(default=' ', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown'), ('restructuredtext', 'Restructured Text')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact',
            field=models.CharField(blank=True, max_length=300, verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=markupfield.fields.MarkupField(blank=True, rendered_field=True, verbose_name='about_text'),
        ),
    ]
