# Generated by Django 2.1.5 on 2019-01-26 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190126_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'Site Settings'},
        ),
    ]
