# Generated by Django 2.1.5 on 2019-01-27 10:22

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20190126_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='_about_text_en_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_en',
            field=markupfield.fields.MarkupField(blank=True, rendered_field=True, verbose_name='about_text EN'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_text_en_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown'), ('restructuredtext', 'Restructured Text')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='contact EN'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='description EN'),
        ),
    ]
