# Generated by Django 2.1.4 on 2019-01-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='text',
            field=models.TextField(max_length=4000, verbose_name='text'),
        ),
    ]
