# Generated by Django 2.1.4 on 2019-01-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.EmailField(max_length=254)),
                ('about_text', models.CharField(max_length=4999)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='page',
            old_name='about_text',
            new_name='text',
        ),
    ]
