# Generated by Django 2.1.5 on 2019-01-26 14:28

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='page',
            name='teaser',
            field=models.CharField(blank=True, max_length=100, verbose_name='teaser'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=markupfield.fields.MarkupField(rendered_field=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(default='', max_length=30, verbose_name='title'),
        ),
    ]
