# Generated by Django 2.1.5 on 2019-01-27 10:22

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190126_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='_text_en_rendered',
            field=models.TextField(default='', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='teaser_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='teaser EN'),
        ),
        migrations.AddField(
            model_name='page',
            name='text_en',
            field=markupfield.fields.MarkupField(default='', rendered_field=True, verbose_name='text EN'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='text_en_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown'), ('restructuredtext', 'Restructured Text')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='page',
            name='title_en',
            field=models.CharField(default='', max_length=30, verbose_name='title EN'),
        ),
    ]
