# Generated by Django 2.1.4 on 2019-01-19 11:14

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20190106_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='_text_rendered',
            field=models.TextField(default=' ', editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='text_markup_type',
            field=models.CharField(choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain'), ('markdown', 'Markdown'), ('restructuredtext', 'Restructured Text')], default='markdown', editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=markupfield.fields.MarkupField(rendered_field=True),
        ),
    ]
